# Generated by Django 5.2.3 on 2026-04-14 00:52

import affiliations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=4, help_text='Ex: 0.1500 = 15%', max_digits=5, verbose_name='Taux de commission')),
                ('tracking_code', models.CharField(db_index=True, default=affiliations.models.generate_tracking_code, max_length=64, unique=True, verbose_name='Code de tracking')),
                ('hmac_signature', models.CharField(blank=True, help_text='Rempli en Phase 3 pour sécuriser les URLs', max_length=128, verbose_name='Signature HMAC')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Lien d'affiliation",
                'verbose_name_plural': "Liens d'affiliation",
            },
        ),
    ]
