# Generated by Django 5.2.3 on 2026-04-14 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliations', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliationlink',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_links', to=settings.AUTH_USER_MODEL, verbose_name='Affilié'),
        ),
        migrations.AddField(
            model_name='affiliationlink',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_links', to='products.product', verbose_name='Produit'),
        ),
        migrations.AlterUniqueTogether(
            name='affiliationlink',
            unique_together={('product', 'affiliate')},
        ),
    ]
