# Generated by Django 5.2.3 on 2026-04-14 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliations', '0002_initial'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliationlink',
            name='hmac_signature',
            field=models.CharField(blank=True, help_text='Cache de la dernière signature générée — recalculée à chaque appel /signed-url/', max_length=128, verbose_name='Dernière signature HMAC'),
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_total', models.DecimalField(decimal_places=2, help_text='Figé au moment du calcul', max_digits=10, verbose_name='Total de la commande')),
                ('commission_rate', models.DecimalField(decimal_places=4, help_text='Figé au moment du calcul — indépendant des modifications futures du lien', max_digits=5, verbose_name='Taux appliqué')),
                ('amount', models.DecimalField(decimal_places=2, help_text='order_total × commission_rate, calculé automatiquement', max_digits=10, verbose_name='Montant de la commission')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validée'), ('paid', 'Versée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions_earned', to=settings.AUTH_USER_MODEL, verbose_name='Affilié')),
                ('affiliation_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='affiliations.affiliationlink', verbose_name="Lien d'affiliation")),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='orders.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
