# Generated by Django 5.2.3 on 2026-04-14 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_templates', to='products.product'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_templates', to='products.pagetemplate'),
        ),
        migrations.AddField(
            model_name='pagetemplate',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='templates', through='products.ProductTemplate', to='products.product', verbose_name='Produits associés'),
        ),
        migrations.AlterUniqueTogether(
            name='producttemplate',
            unique_together={('product', 'template')},
        ),
    ]
