# Generated by Django 5.2.3 on 2026-04-14 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetemplate',
            name='critical_css',
            field=models.TextField(blank=True, help_text='Blob CSS généré automatiquement à la sauvegarde du template. Élimine le calcul au rendu.', verbose_name='Critical CSS'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Utilisé par les règles de visibilité conditionnelle des blocs', verbose_name='Stock'),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mon thème', max_length=100, verbose_name='Nom du thème')),
                ('variables', models.JSONField(default=dict, help_text='Dict de variables CSS : {"primary_color": "#FF6B35", "font_family": "Inter"}', verbose_name='Variables CSS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Thème',
                'verbose_name_plural': 'Thèmes',
            },
        ),
    ]
