# Generated by Django 5.2.3 on 2026-04-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_phase4_jsonb_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, help_text='Ex: Technologie, SaaS, Formation, Physique', max_length=100, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Incrémenté à chaque appel GET /render/<id>/', verbose_name='Nombre de vues'),
        ),
    ]
