# Generated by Django 5.2.3 on 2026-04-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_phase5_views_count_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_main',
            field=models.ImageField(blank=True, help_text='Image principale affichée sur la page de vente et dans le catalogue', null=True, upload_to='products/images/', verbose_name='Image principale'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_secondary_1',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='Image secondaire 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_secondary_2',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='Image secondaire 2'),
        ),
    ]
